export const USER_CREATED = 'USER_CREATED';

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const CARD_CREATED = 'CARD_CREATED';
export const CARD_DELETED = 'CARD_DELETED';
export const THEME_CREATED = 'THEME_CREATED';
export const THEME_DELETED= 'THEME_DELETED';
export const SUBJECT_CREATED = 'SUBJECT_CREATED';
export const SUBJECT_DELETED = 'SUBJECT_DELETED';
export const SUBJECT_SHARED = 'SUBJECT_SHARED';
export const COMMENT_ADDED = 'COMMENT_ADDED';

export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN'; 
export const RECEIVE_USER_LOGIN = 'RECEIVE_USER_LOGIN'; 
export const FAILURE_USER_LOGIN = 'FAILURE_USER_LOGIN'; 
export const USER_LOGGED_IN = 'USER_LOGGED_IN';

export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";